/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.facebook.facebook.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.facebook.facebook.service.FacebookQueryExecutorService;
import com.facebook.facebook.models.query.*;

@RestController(value = "Facebook.QueryExecutionController")
@RequestMapping("/facebook/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private FacebookQueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @GetMapping(value = "/queries/getLoggedUserPosts")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "get posts of loggin user")
    public Page<GetLoggedUserPostsResponse> executeGetLoggedUserPosts(@RequestParam(value = "logged_user_id") String loggedUserId, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: getLoggedUserPosts");
        Page<GetLoggedUserPostsResponse> _result = queryService.executeGetLoggedUserPosts(loggedUserId, pageable);
        LOGGER.debug("got the result for named query: getLoggedUserPosts, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file url for query getLoggedUserPosts")
    @PostMapping(value = "/queries/getLoggedUserPosts/export")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportGetLoggedUserPosts(@RequestParam(value = "logged_user_id") String loggedUserId, @RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: getLoggedUserPosts");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "getLoggedUserPosts";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportGetLoggedUserPosts(loggedUserId,  exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

}