/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.facebook.facebook;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EducationType generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`education_type`")
public class EducationType implements Serializable {

    private Integer id;
    private String eduType;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`edu_type`", nullable = false, length = 30)
    public String getEduType() {
        return this.eduType;
    }

    public void setEduType(String eduType) {
        this.eduType = eduType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EducationType)) return false;
        final EducationType educationType = (EducationType) o;
        return Objects.equals(getId(), educationType.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}