/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.facebook.facebook.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetLoggedUserPostsResponse implements Serializable {


    @ColumnAlias("id")
    private Long id;

    @ColumnAlias("from_user_id")
    private Long fromUserId;

    @ColumnAlias("with_user_id")
    private Long withUserId;

    @ColumnAlias("post_type_id")
    private Long postTypeId;

    @ColumnAlias("post")
    private String post;

    @ColumnAlias("created_at")
    private Timestamp createdAt;

    @ColumnAlias("post_content")
    private String postContent;

    @ColumnAlias("likes")
    private Long likes;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFromUserId() {
        return this.fromUserId;
    }

    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    public Long getWithUserId() {
        return this.withUserId;
    }

    public void setWithUserId(Long withUserId) {
        this.withUserId = withUserId;
    }

    public Long getPostTypeId() {
        return this.postTypeId;
    }

    public void setPostTypeId(Long postTypeId) {
        this.postTypeId = postTypeId;
    }

    public String getPost() {
        return this.post;
    }

    public void setPost(String post) {
        this.post = post;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public String getPostContent() {
        return this.postContent;
    }

    public void setPostContent(String postContent) {
        this.postContent = postContent;
    }

    public Long getLikes() {
        return this.likes;
    }

    public void setLikes(Long likes) {
        this.likes = likes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetLoggedUserPostsResponse)) return false;
        final GetLoggedUserPostsResponse getLoggedUserPostsResponse = (GetLoggedUserPostsResponse) o;
        return Objects.equals(getId(), getLoggedUserPostsResponse.getId()) &&
                Objects.equals(getFromUserId(), getLoggedUserPostsResponse.getFromUserId()) &&
                Objects.equals(getWithUserId(), getLoggedUserPostsResponse.getWithUserId()) &&
                Objects.equals(getPostTypeId(), getLoggedUserPostsResponse.getPostTypeId()) &&
                Objects.equals(getPost(), getLoggedUserPostsResponse.getPost()) &&
                Objects.equals(getCreatedAt(), getLoggedUserPostsResponse.getCreatedAt()) &&
                Objects.equals(getPostContent(), getLoggedUserPostsResponse.getPostContent()) &&
                Objects.equals(getLikes(), getLoggedUserPostsResponse.getLikes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getFromUserId(),
                getWithUserId(),
                getPostTypeId(),
                getPost(),
                getCreatedAt(),
                getPostContent(),
                getLikes());
    }
}